from .base import BaseSatellite
from .gf1 import GF1Satellite
from .gf2 import GF2Satellite
from .gf3 import GF3Satellite
from .gf4 import GF4Satellite
from .gf5 import GF5Satellite
from .gf6 import GF6Satellite
from .gf7 import GF7Satellite
from .gf1b import GF1BSatellite
from .gf1c import GF1CSatellite
from .gf1d import GF1DSatellite
from .sv101 import SV101Satellite
from .sv102 import SV102Satellite
from .sv103 import SV103Satellite
from .sv104 import SV104Satellite
